### ISSUE TITLE
Internal API is accessed

### ISSUE THREAD

**Issue by nicity** [manifold-systems/manifold#21]
Plugin (e.g. v.0.24-alpha) is not compatible with internal API changes in com.intellij.util.lang.ClasspathCache.LoaderData and its loading will be rejected by IDE.

https://github.com/manifold-systems/manifold/blob/54e07cd30d33e4f84644d270970831d4f8612208/manifold-core-parent/manifold/src/main/java/manifold/internal/runtime/IjPluginIntegration.java#L16

**Comment by rsmckinney** [comment]
Can you elaborate?  What version of IJ are you referring to?  Is there a stack trace?  Thanks!

**Comment by nicity** [comment]
IJ 2019.1 (master of https://github.com/JetBrains/intellij-community)
Commit that disables loading of v. 0.24-alpha https://github.com/JetBrains/intellij-community/commit/e676f05d5a4cad697b05d697f9564b6b2e2ff48c

**Comment by rsmckinney** [comment]
Ah, thanks for the heads up.  I see the recent changes to ClasspathCache etc.  I'll fix this in the next release of the plugin, probably available for use in a few days (it takes JetBrains a couple of days on average to approve a plugin update).  Let me know if you need it sooner, I can provide a build for you.

**Comment by rsmckinney** [comment]
Fixed with plugin update [0.25.2-alpha](https://plugins.jetbrains.com/plugin/10057-manifold/update/51198) (pending repo review).  Tested with CR master (2019).

Thanks again for reporting this.

**Comment by nicity** [comment]
Plugin v0.25.2-alpha still isn't compatible

Plugin URL: https://plugins.jetbrains.com/plugin/index?xmlId=manifold.ij
Plugin: manifold.ij:0.25.2-alpha
Method com.intellij.util.lang.UrlLoader.buildData() : com.intellij.util.lang.ClasspathCache.LoaderData contains an *invokespecial* instruction referencing an unresolved constructor com.intellij.util.lang.ClasspathCache.LoaderData.<init>(). This can lead to **NoSuchMethodError** exception at runtime.
This problem takes place against IU-191.724 but not against IU-182.3341.11

**Comment by rsmckinney** [comment]
The Manifold plugin loads the `com.intellij.util.lang.UrlLoader` class inside the parent of the PluginClassLoader where the IJ classes, including `com.intellij.util.lang.ClasspathCache.LoaderData`, reside. Thus my suspicion is, since IJ's plugin verifier does not take this into account, it flags the _invokespecial_ call as 'unresolved' assuming the package-private constructor can't be accessed from a plugin class.

Some background.  The Manifold plugin uses Manifold itself to target multiple versions of IJ.  Specifically, it uses Manifold's [Dark Java](http://manifold.systems/docs.html#dark-java) feature to manage multiple versions of classes each targeting a different version of IJ.  Essentially, Dark Java dynamically compiles and loads the release-specific classes at runtime, thereby avoiding the complications otherwise involved with multi-release jars.

The static nature of the IJ plugin verifier prohibits it from sorting out code specific to IJ releases. However, I'd like to suggest a possible solution to this.  

The IJ plugin API could provide an annotation, say `@VersionRange`, where plugin authors can isolate and identify code that pertains to a specific range of IJ versions.  For example:

```java
@VersionRange(from=173, to=182)
public void loadXxxExtensionSupporting173() { ... }

@VersionRange(from=182)
public void loadXxxExtensionSupporting82() { ... }
``` 
As such the IJ plugin verifier can statically identify regions of code it should exclude from analysis.  This would avoiding false positives such as the one in this post.

Sound reasonable?

**Comment by nicity** [comment]
IMO your idea seems to be reasonable in general but of limited use case for automated API validations we are started to enforce, both for IDE and plugin developers.
Anyway, having two plugin versions that target different IDE versions seems to be more simple way to live right now.
