### ISSUE TITLE
Delegation fails to automatically delegate getters/setters for interface properties.

### ISSUE THREAD

**Issue by EotT123** [manifold-systems/manifold#644]
**Describe the bug**
When using interface properties with delegation, I am required to manually re-implement the getters and/or setters for those properties, rather than having them automatically delegated to the delegate object. Consider the following example:

```java
public interface TestIntf {
   @var Object object;
}

public class Test implements TestIntf {
   @override @var Object object;
}

public class DelegationTest implements TestIntf {
   @link Test delegate;

   public DelegationTest(Test delegate){
      this.delegate = delegate;
   }
   // Error! I'm forced to implement the following methods.
   // @Override public Object getObject() { ... }
   // @Override public void setObject(Object value) {  ... }
}
```
I would expect the getter and setter methods to be automatically delegated to the delegate object, but instead, I am forced to implement them manually.

When replacing the interface properties with getter and setter methods, I'm not required anymore to implement them when using delegation.
```java
public interface TestIntf {
   Object getObject();
   Object setObject(Object object);
}

public class DelegationTest implements TestIntf {
   @link Test delegate;

   public DelegationTest(Test delegate){
      this.delegate = delegate;
   }
   // No error!
}
```

**Desktop (please complete the following information):**
- OS Type & Version: Windows 10 22H2
- Java/JDK version: openjdk 23.0.1
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ IDEA 2024.3
- Manifold version: 2024.1.42 (latest version)
- Manifold IntelliJ plugin version: 2024.1.13 (latest version)

**Comment by rsmckinney** [comment]
Note, this is just an IntelliJ limitation at the moment, your project will still compile. This will be fixed soon. Thanks for reporting.

**Comment by rsmckinney** [comment]
Fix available with release 2024.1.43

**Comment by EotT123** [comment]
Thanks for the fix. However, it doesn't seem to fix the problem. I'm still encountering the exact same issue.

**Comment by rsmckinney** [comment]
Fix available with release 2025.1.3, and latest IJ plugin releases.

**Comment by EotT123** [comment]
This still doesn't seem to be fixed, I'm using plugin 2024.1.24, IntelliJ IDEA 2024.3.4.1. I assume the IntelliJ version I'm using should also work?

**Comment by rsmckinney** [comment]
Whoops, thanks for the heads-up. The fix went into the 2025 EA branch, didn't make it into the 2024 branch. It should be available in IJ 2024 by EOD Monday (JB doesn't update Marketplace over weekends)

**Comment by EotT123** [comment]
Apparently, the plugin was already updated by JB. The error is gone now, thanks.
