### ISSUE TITLE
Bug when using property inference and extending classes

### ISSUE THREAD

**Issue by EotT123** [manifold-systems/manifold#646]
**Describe the bug**
When using `manifold-props`, the following code of produces an error:

```java
public abstract class Parent {
    protected Object foo = null;

    public Object getFoo() {
        return foo;
    }
}

public class Child extends Parent{
    public Object getFoo() {
        if (foo == null) {
            foo = new Object(); // ERROR: Cannot assign read-only property 'foo '
        }
        return foo;
    }
}
```
The issue arises when attempting to set the `foo` field in the class `Child`, which is a (non private) field in the superclass `Parent`. Due to property inference, only a getter is available for `foo`, causing the assignment to result in the error: `Cannot assign read-only property 'foo'`.

If the `getFoo()` method is omitted from the `Parent` class, the issue does not occur. Removing `manifold-props` also resolves the problem.

**Desktop (please complete the following information):**
- OS Type & Version: Windows 10 22H2
- Java/JDK version: openjdk 23.0.1
- IDE version (IntelliJ IDEA or Android Studio): IntelliJ IDEA 2024.3
- Manifold version: 2024.1.42 (latest version)
- Manifold IntelliJ plugin version: 2024.1.13 (latest version)

**Comment by EotT123** [comment]
I encountered this error in class `javax.swing.text.JTextComponent`:

```java
public abstract class JTextComponent extends JComponent {
    ...
    public AccessibleContext getAccessibleContext() {
        if (accessibleContext == null) {
            accessibleContext = new AccessibleJTextComponent();
        }
        return accessibleContext;
    }
    ...
}
```

One of the parents of `JTextComponent` is `java.awt.Component`, which contains the `accessibleContext` field, and a getter method:
```java
public abstract class Component {
    ...
    protected AccessibleContext accessibleContext = null;

    public AccessibleContext getAccessibleContext() {
        return accessibleContext;
    }
    ....
}
```

**Comment by rsmckinney** [comment]
Fix available with release 2024.1.43

**Comment by EotT123** [comment]
Thanks for the fix. However, it doesn't seem to fix the problem.  I'm still encountering the exact same error when building with Maven.

**Comment by rsmckinney** [comment]
Fix available with release 2025.1.3

**Comment by EotT123** [comment]
Thanks, it's working now.
